# Generated by Django 3.0.6 on 2020-06-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('created',), 'verbose_name_plural': ''},
        ),
    ]
