# Generated by Django 3.0.6 on 2020-06-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='highligted',
            new_name='highlighted',
        ),
    ]
